apiVersion: v1
kind: Service
metadata:
  name: prestashop
  namespace: 4kube
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: prestashop
  selector:
    app: prestashop
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: 4kube
spec:
  type: NodePort
  ports:
  - port: 3306
    name: mariadb
  selector:
    app: mariadb